name: Fetch Weather Data

on:
  push:
  pull_request:
  merge_group:
  #schedule:
    # - cron: '30 4 * * *'  # Run the job daily at 4:30

jobs:
  fetch_weather:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Python script
      run: python canada.py
